In [2]:
!pip3 install finterstellar

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting finterstellar
  Downloading finterstellar-0.1.19-py3-none-any.whl (12 kB)
Collecting pandas-datareader>=0.10.0
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
     |████████████████████████████████| 109 kB 5.1 MB/s
Requirement already satisfied: numpy>=1.19.3 in /usr/local/lib/python3.7/dist-packages (from finterstellar) (1.21.6)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.7/dist-packages (from finterstellar) (1.3.5)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.7/dist-packages (from finterstellar) (2.23.0)
Requirement already satisfied: lxml>=4.2.6 in /usr/local/lib/python3.7/dist-packages (from finterstellar) (4.9.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1.4->finterstellar) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1.4->finterstellar) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.1.4->finterstellar) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.23.0->finterstellar) (2022.9.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.23.0->finterstellar) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.23.0->finterstellar) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.23.0->finterstellar) (3.0.4)
Installing collected packages: pandas-datareader, finterstellar
  Attempting uninstall: pandas-datareader
    Found existing installation: pandas-datareader 0.9.0
    Uninstalling pandas-datareader-0.9.0:
      Successfully uninstalled pandas-datareader-0.9.0
Successfully installed finterstellar-0.1.19 pandas-datareader-0.10.0

In [3]:
import finterstellar as fs

In [12]:
OTP = "16684897351011151161"

In [15]:
df = fs.fn_single(otp = OTP, symbol='COST', window="T")
df.tail(3)

,Revenue,COGS,Gross Profit,SG&A,Operating Income,Net Income,EPS,EBITDA,EBIT,Shares,...,Long Term Liabilities,Total Liabilities,Shareholders Equity,Depreciation,Operating Cash Flow,Capital Expenditure,Investing cash flow,Dividends,Financing cash flow,Price
2022-04-30,2.175380e+11,1.905570e+11,2.698100e+10,1.937500e+10,7.571000e+09,5.646000e+09,12.70,9.808000e+09,7.571000e+09,444000000.0,...,1.149400e+10,4.333900e+10,1.996800e+10,2.202000e+09,7.826000e+09,-2.872000e+09,-3.583000e+09,-698000000.0,-3.062000e+09,531.72
2022-05-31,2.074590e+11,1.821790e+11,2.528000e+10,1.819300e+10,7.087000e+09,5.329000e+09,11.99,9.071000e+09,7.087000e+09,443700000.0,...,1.149400e+10,4.333900e+10,2.051300e+10,1.984000e+09,6.113000e+09,-2.632000e+09,-3.463000e+09,-351000000.0,-3.019000e+09,466.22
2022-08-31,2.291870e+11,2.017850e+11,2.740200e+10,1.951100e+10,7.891000e+09,5.873000e+09,13.21,1.010200e+10,7.891000e+09,444000000.0,...,1.152100e+10,4.351900e+10,2.064200e+10,2.211000e+09,5.361000e+09,-1.577000e+09,-4.880000e+09,700000000.0,-3.278000e+09,522.10